export const MenuData = [
    {
        id:0,title:"美食",url:"/#",imgUrl:"/static/icons/icon_28.gif"
    },
    {
        id:1,title:"美食",url:"/#",imgUrl:"/static/icons/icon_29.gif"
    },
    {
        id:2,title:"美食",url:"/#",imgUrl:"/static/icons/icon_30.gif"
    },
    {
        id:3,title:"美食",url:"/#",imgUrl:"/static/icons/icon_31.gif"
    },
    {
        id:4,title:"美食",url:"/#",imgUrl:"/static/icons/icon_32.gif"
    },
    {
        id:5,title:"美食",url:"/#",imgUrl:"/static/icons/icon_18.gif"
    },
    {
        id:6,title:"美食",url:"/#",imgUrl:"/static/icons/icon_19.gif"
    },
    {
        id:7,title:"美食",url:"/#",imgUrl:"/static/icons/icon_20.gif"
    },
    {
        id:8,title:"美食",url:"/#",imgUrl:"/static/icons/icon_21.gif"
    },
    {
        id:9,title:"美食",url:"/#",imgUrl:"/static/icons/icon_22.gif"
    }
];